source("health calculations/functions.R")
cn <- append("baseline_mmet", grep('MS',names(health_mmets), value = TRUE))
mmets <- health_mmets
names(mmets)[names(mmets)=="f.hmmets$health_mmets"] <- "baseline_mmet"
baseline <- create_baseline(bl)
rr <- mmet2RR(mmets, mmet2RR_mat, cn)
rr <- inner_join(rr, subset(baseline, select = c("ID", "age_group", "Sex_B01ID")), by = "ID")
people_with_no_trips_rr <- mmet2RR(people_with_no_trips, mmet2RR_mat, "health_mmets")
pif <- PAF(pop = rr, non_travel_mmet = people_with_no_trips_rr)
pif <- data.frame(pif)
pif <- arrange(pif, age.band, gender)
gbd <- read.csv("health calculations/gbd_18_84.csv", header = T, as.is = T)
gbd <- arrange(gbd, age, gender)
yll <- combine_health_and_pif(pif, gbd, "yll")
yll_red <- calculate_health_reductions(pif, gbd, td, hm = "yll")
